import { query } from '../config/db.js';
import { hashPassword } from '../utils/auth.js';
import { validateUserInput, emailRegex, passwordRegex } from '../utils/validation.js';
const allowedRoles=['ADMIN','USER','OWNER'];
function sort(column, direction){ const cols={name:'name',email:'email',address:'address',role:'role',rating:'rating'}; return `${cols[column]||'name'} ${direction==='desc'?'DESC':'ASC'}`; }
export async function dashboard(req,res){ const [u,s,r]=await Promise.all([query('SELECT COUNT(*)::int count FROM users'),query('SELECT COUNT(*)::int count FROM stores'),query('SELECT COUNT(*)::int count FROM ratings')]); res.json({users:u.rows[0].count,stores:s.rows[0].count,ratings:r.rows[0].count}); }
export async function users(req,res){ const {name='',email='',address='',role='',sortBy='name',sortDir='asc'}=req.query; const params=[]; const where=[]; for(const [field,val] of [['name',name],['email',email],['address',address]]){if(val){params.push(`%${val}%`);where.push(`${field} ILIKE $${params.length}`);}} if(role&&allowedRoles.includes(role)){params.push(role);where.push(`role=$${params.length}`);} const q=`SELECT id,name,email,address,role,created_at FROM users ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY ${sort(sortBy,sortDir)}`; const r=await query(q,params); res.json(r.rows); }
export async function stores(req,res){ const {name='',email='',address='',sortBy='name',sortDir='asc'}=req.query; const params=[]; const where=[]; for(const [field,val] of [['s.name',name],['s.email',email],['s.address',address]]){if(val){params.push(`%${val}%`);where.push(`${field} ILIKE $${params.length}`);}} const q=`SELECT s.id,s.name,s.email,s.address,COALESCE(ROUND(AVG(r.rating)::numeric,2),0) rating FROM stores s LEFT JOIN ratings r ON r.store_id=s.id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY s.id ORDER BY ${sort(sortBy==='rating'?'rating':sortBy,sortDir)}`; res.json((await query(q,params)).rows); }
export async function addUser(req,res){ const {name,email,password,address,role}=req.body; if(!allowedRoles.includes(role)) return res.status(400).json({message:'Invalid role.'}); const errors=validateUserInput({name,email,password,address}); if(Object.keys(errors).length)return res.status(400).json({message:'Validation failed.',errors}); const exists=await query('SELECT id FROM users WHERE LOWER(email)=LOWER($1)',[email.trim()]); if(exists.rowCount)return res.status(409).json({message:'Email already exists.'}); const hash=await hashPassword(password); const r=await query('INSERT INTO users(name,email,password_hash,address,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,address,role',[name.trim(),email.trim().toLowerCase(),hash,address.trim(),role]); res.status(201).json(r.rows[0]); }
export async function addStore(req,res){ const {name,email,address,ownerId}=req.body; if(typeof name!=='string'||name.trim().length<20||name.trim().length>60)return res.status(400).json({message:'Store name must be between 20 and 60 characters.'}); if(!emailRegex.test(email||''))return res.status(400).json({message:'Invalid email.'}); if(!address||address.trim().length>400)return res.status(400).json({message:'Address is required and must be at most 400 characters.'}); const owner=await query("SELECT id FROM users WHERE id=$1 AND role='OWNER'",[ownerId]); if(!owner.rowCount)return res.status(400).json({message:'A valid Store Owner is required.'}); try { const r=await query('INSERT INTO stores(name,email,address,owner_id) VALUES($1,$2,$3,$4) RETURNING *',[name.trim(),email.trim().toLowerCase(),address.trim(),ownerId]); res.status(201).json(r.rows[0]); } catch(e){res.status(409).json({message:'Store email or owner is already assigned.'});} }
export async function details(req,res){ const r=await query(`SELECT u.id,u.name,u.email,u.address,u.role, CASE WHEN u.role='OWNER' THEN COALESCE((SELECT ROUND(AVG(rt.rating)::numeric,2) FROM stores st LEFT JOIN ratings rt ON rt.store_id=st.id WHERE st.owner_id=u.id),0) END AS rating FROM users u WHERE u.id=$1`,[req.params.id]); if(!r.rowCount)return res.status(404).json({message:'User not found.'}); res.json(r.rows[0]); }
export async function owners(req,res){ const r=await query("SELECT id,name,email FROM users WHERE role='OWNER' ORDER BY name"); res.json(r.rows); }
